### ISSUE TITLE
运行的时候报错，还没发起请求，用的main分支

### ISSUE THREAD

**Issue by zhangyebo1991** [HXSecurity/DongTai-agent-go#11]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\john\go #gosetup
"C:\Program Files\Go\bin\go.exe" build -o C:\Users\john\AppData\Local\Temp\GoLand\___1go_build_example_com_mod.exe example.com/mod #gosetup
C:\Users\john\AppData\Local\Temp\GoLand\___1go_build_example_com_mod.exe
open dongtai-go-agent-config.yaml: The system cannot find the file specified.
等待当前程序http启动完成
SqlDBQuery
Sprintf
JsonUnmarshal
JsonDecoderDecode
JsonNewDecoder
RuntimeConcatstrings
ExecCommand
execCmdRun
BufioWriterWrite
BufioWriterWriteString
RuntimesSringtoslicebyte
HtmlTemplateExecuteTemplate
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
syscall.UTF16PtrFromString(...)
        C:/Program Files/Go/src/syscall/syscall_windows.go:101
syscall.LoadDLL({0x9b573b, 0x28})
        C:/Program Files/Go/src/syscall/dll_windows.go:73 +0x2a5
syscall.(*LazyDLL).Load(0xc0001237e0)
        C:/Program Files/Go/src/syscall/dll_windows.go:248 +0xa5
syscall.(*LazyProc).Find(0xc000300300)
        C:/Program Files/Go/src/syscall/dll_windows.go:303 +0xa5
github.com/mattn/go-isatty.init.0()
        E:/GO/hello/vendor/github.com/mattn/go-isatty/isatty_windows.go:31 +0x25

Process finished with the exit code 2

**Comment by piexlmax** [comment]
https://iast-test.huoxian.cn/deploy 注意文档最后一步：
添加命令行参数 -gcflags "all=-N -l" 运行项目,例如： go run -gcflags "all=-N -l" main.go

**Comment by zhangyebo1991** [comment]
> https://iast.io/deploy 注意文档最后一步： 添加命令行参数 -gcflags "all=-N -l" 运行项目,例如： go run -gcflags "all=-N -l" main.go

你好，这个网站我登录不进去，提示登录失败

**Comment by piexlmax** [comment]
https://demo.iast.io/  点击右上角的 add Agent+
